language: go

matrix:
  include:
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=off
    - go: "1.11.x"
      env: GO111MODULE=on
    - go: tip

install:
  - go get -d -v ./...

script:
  - ./.travis.gofmt.sh
  - ./.travis.govet.sh
  - go test -v -race 